version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - errorlint
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - gomoddirectives
    - gosec
    - ireturn
    - lll
    - maintidx
    - mnd
    - nlreturn
    - noctx
    - promlinter
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - staticcheck
    - noinlineerr
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    gosec:
      excludes:
        - G402
        - G404
    revive:
      rules:
        - name: var-declaration
          disabled: true
    staticcheck:
      checks:
        - all
        - -SA1019
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
